name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        node:
          - 16.x
        adapter:
          - local
          - redis
          - cluster
        app_manager:
          - array
          - mysql
          - postgres
          - dynamodb

        include:
          - adapter: local
            rate_limiter: local
            queue_driver: sync
          - adapter: cluster
            rate_limiter: cluster
            queue_driver: sync
          - adapter: redis
            rate_limiter: redis
            queue_driver: redis

    name: Node.js ${{ matrix.node }} (adapter:${{ matrix.adapter }} manager:${{ matrix.app_manager }} ratelimiter:${{ matrix.rate_limiter }} queue:${{ matrix.queue_driver }})

    steps:
      - uses: actions/checkout@v2.4.0

      - uses: actions/setup-node@v2.5.1
        name: Setup Node.js v${{ matrix.node }}
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Execute lint & build
        run: |
          npm run lint
          npm run build

      - name: Setup Redis
        if: "matrix.adapter == 'redis' || matrix.adapter == 'cluster'"
        run: docker run -p 6379:6379 redis:6-alpine &

      # Setup MySQL with user `root`, password `root` and database `testing`
      - name: Setup MySQL
        if: "matrix.app_manager == 'mysql'"
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE testing;' -u root -proot
          mysql -u root -proot --database=testing < tests/fixtures/mysql_schema.sql

      # Setup PostgreSQL with user `testing`, password `testing` and database `testing`
      - name: Setup PostgreSQL
        if: "matrix.app_manager == 'postgres'"
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres psql --command="CREATE USER testing PASSWORD 'testing'"
          sudo -u postgres createdb --owner=postgres testing
          psql --host=127.0.0.1 --username=testing testing < tests/fixtures/postgres_schema.sql
        env:
          PGPASSWORD: testing

      - name: Setup DynamoDB
        if: "matrix.app_manager == 'dynamodb'"
        run: |
          docker run -p 8000:8000 amazon/dynamodb-local &
          node tests/fixtures/dynamodb_schema.js
        env:
          AWS_ACCESS_KEY_ID: fake-id
          AWS_SECRET_ACCESS_KEY: fake-secret

      - name: Execute tests
        run: npm run test
        env:
          TEST_ADAPTER: ${{ matrix.adapter }}
          TEST_APP_MANAGER: ${{ matrix.app_manager }}
          TEST_QUEUE_DRIVER: ${{ matrix.queue_driver }}
          TEST_RATE_LIMITER: ${{ matrix.rate_limiter }}
          TEST_MYSQL_USER: root
          TEST_MYSQL_PASSWORD: root
          AWS_ACCESS_KEY_ID: fake-id
          AWS_SECRET_ACCESS_KEY: fake-secret

      - uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
